name: auth_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  get_it: ^7.6.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  dart_mappable: ^4.1.0
  injectable: ^2.3.2
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  dart_mappable_builder: ^4.1.0

flutter:
  uses-material-design: true
